services:
  - type: web
    name: sakina-fuel-tracker
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python manage.py migrate && python manage.py collectstatic --noinput && gunicorn fuel_project.wsgi:application --host=0.0.0.0 --port=$PORT
    envVars:
      - key: DEBUG
        value: False
      - key: DJANGO_SETTINGS_MODULE
        value: fuel_project.settings

databases:
  - name: sakina-fuel-db
    plan: free