# Generated by Django 5.2.1 on 2025-05-14 07:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='bol_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique_for_date='loading_date', verbose_name='BOL Number'),
        ),
        migrations.AddField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('LOADING', 'Loading'), ('LOADED', 'Loaded'), ('GATEPASSED', 'Gatepassed'), ('TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='trip',
            name='loading_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='BOL Date'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='loading_time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='BOL Time'),
        ),
    ]
