# Generated by Django 5.2.1 on 2025-05-14 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0002_trip_bol_number_trip_status_alter_trip_loading_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipment',
            options={'ordering': ['import_date', 'created_at']},
        ),
        migrations.RenameField(
            model_name='loadingcompartment',
            old_name='quantity_loaded_litres',
            new_name='quantity_requested_litres',
        ),
        migrations.AddField(
            model_name='shipment',
            name='quantity_remaining',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='loadingcompartment',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_compartments', to='shipments.trip'),
        ),
        migrations.CreateModel(
            name='ShipmentDepletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_depleted', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipment_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depletions_from_batch', to='shipments.shipment')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depletions_for_trip', to='shipments.trip')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
