# Generated by Django 5.2.1 on 2025-05-16 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0004_populate_shipment_quantity_remaining'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='vessel_id_tag',
            field=models.CharField(blank=True, help_text='The unique identification tag for the shipment (e.g., AGO KG09/2025). Must be unique after initial data population.', max_length=100, null=True, unique=True, verbose_name='Vessel ID / Shipment Unique ID'),
        ),
    ]
