# Generated by Django 5.2.1 on 2025-05-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0006_alter_shipment_vessel_id_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='vessel_id_tag',
            field=models.CharField(blank=True, help_text='The unique identification tag for the shipment (e.g., AGO KG09/2025). Must be unique after initial data population.', max_length=100, null=True, unique=True, verbose_name='Vessel ID / Shipment Unique ID'),
        ),
    ]
