# Generated by Django 5.2.1 on 2025-05-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0007_alter_shipment_vessel_id_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='vessel_id_tag',
            field=models.CharField(default='SHOULD_BE_POPULATED', help_text='The unique identification tag for the shipment (e.g., AGO KG09/2025). This field is required and must be unique.', max_length=100, unique=True, verbose_name='Vessel ID / Shipment Unique ID'),
            preserve_default=False,
        ),
    ]
