# Generated by Django 5.2.1 on 2025-05-19 13:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0008_alter_shipment_vessel_id_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='trip',
            name='kpc_comments',
            field=models.TextField(blank=True, help_text='Comments from KPC emails', null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='kpc_loading_order_no',
            field=models.CharField(blank=True, help_text='KPC Loading Order No (e.g., S02106)', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='bol_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Final BOL Number'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='loading_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Planned/Actual BOL Date'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='loading_time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Planned/Actual BOL Time'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('PENDING_KPC_APPROVAL', 'Pending KPC Approval'), ('KPC_REJECTED', 'KPC Rejected'), ('KPC_APPROVED', 'KPC Approved'), ('PENDING', 'Pending Loading'), ('LOADING', 'Loading'), ('LOADED', 'Loaded'), ('GATEPASSED', 'Gatepassed'), ('TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING_KPC_APPROVAL', max_length=30),
        ),
        migrations.AddField(
            model_name='shipment',
            name='depot',
            field=models.ForeignKey(blank=True, help_text='Depot where this shipment was received.', null=True, on_delete=django.db.models.deletion.PROTECT, to='shipments.depot'),
        ),
        migrations.AddField(
            model_name='trip',
            name='depot',
            field=models.ForeignKey(blank=True, help_text='Depot this trip is loading from.', null=True, on_delete=django.db.models.deletion.PROTECT, to='shipments.depot'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='destination',
            field=models.ForeignKey(blank=True, help_text='Intended final destination for this stock batch.', null=True, on_delete=django.db.models.deletion.PROTECT, to='shipments.destination'),
        ),
        migrations.AddField(
            model_name='trip',
            name='destination',
            field=models.ForeignKey(blank=True, help_text='Final destination for this trip.', null=True, on_delete=django.db.models.deletion.PROTECT, to='shipments.destination'),
        ),
    ]
