# Generated by Django 5.2.1 on 2025-05-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0009_depot_destination_trip_kpc_comments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='depot',
        ),
        migrations.AlterField(
            model_name='trip',
            name='bol_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Final BOL Number (KPC Shipment No from PDF)'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='kpc_loading_order_no',
            field=models.CharField(blank=True, help_text='KPC Loading Order No (e.g., S02106) from Authority PDF', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('PENDING_AUTHORITY', 'Pending Loading Authority'), ('KPC_REJECTED', 'KPC Rejected'), ('KPC_APPROVED', 'KPC Approved'), ('PENDING_LOADING', 'Pending Actual Loading'), ('LOADING', 'Loading'), ('LOADED', 'Loaded (Awaiting Gatepass / BoL)'), ('GATEPASSED', 'Gatepassed'), ('TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING_AUTHORITY', max_length=30),
        ),
    ]
