# Generated by Django 5.2.1 on 2025-05-20 06:58

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0010_remove_shipment_depot_alter_trip_bol_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='depot',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='kpc_loading_order_no',
        ),
        migrations.AddField(
            model_name='destination',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 5, 20, 6, 58, 8, 32487, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='name',
            field=models.CharField(help_text='e.g., South Sudan, DRC, Local Nairobi', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='destination',
            field=models.ForeignKey(blank=True, help_text='Destination this shipment is earmarked for, if any.', null=True, on_delete=django.db.models.deletion.PROTECT, to='shipments.destination'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='bol_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='KPC Order No / Final BOL No'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='destination',
            field=models.ForeignKey(help_text='Destination for this loading.', null=True, on_delete=django.db.models.deletion.PROTECT, to='shipments.destination'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='loading_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='BOL Date'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='loading_time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='BOL Time'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('LOADING', 'Loading'), ('LOADED', 'Loaded'), ('GATEPASSED', 'Gatepassed'), ('TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.DeleteModel(
            name='Depot',
        ),
    ]
