# Generated by Django 5.2.1 on 2025-05-20 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0012_alter_trip_destination_alter_trip_loading_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='destination',
            field=models.ForeignKey(default=2, help_text='Destination for this loading.', on_delete=django.db.models.deletion.PROTECT, to='shipments.destination'),
            preserve_default=False,
        ),
    ]
