# Generated by Django 5.2.1 on 2025-05-20 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0013_alter_trip_destination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='capacity_ago',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='capacity_pms',
        ),
    ]
