# Generated by Django 5.2.1 on 2025-05-21 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0014_remove_vehicle_capacity_ago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadingcompartment',
            name='density',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='loadingcompartment',
            name='quantity_actual_l20',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='loadingcompartment',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='kpc_order_number',
            field=models.CharField(blank=True, help_text='Original KPC Loading Order No (e.g., Sxxxxx) from Authority PDF.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='bol_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Final BoL No / KPC Shipment No'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending KPC Action'), ('KPC_APPROVED', 'KPC Approved (Stock Booked)'), ('KPC_REJECTED', 'KPC Rejected'), ('LOADING', 'Loading @ Depot'), ('LOADED', 'Loaded from Depot (BoL Received)'), ('GATEPASSED', 'Gatepassed from Depot'), ('TRANSIT', 'In Transit to Customer'), ('DELIVERED', 'Delivered to Customer'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=30),
        ),
    ]
