# Generated by Django 5.2.1 on 2025-05-21 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0015_loadingcompartment_density_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='kpc_order_number',
            field=models.CharField(default='UNKNOWN_KPC_ORDER', help_text='KPC Loading Order No (e.g., Sxxxxx) from Authority PDF. Required and must be unique.', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
