# Generated by Django 5.2.1 on 2025-05-29 12:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0016_alter_trip_kpc_order_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['name'], name='shipments_c_name_f4a852_idx'),
        ),
        migrations.AddIndex(
            model_name='destination',
            index=models.Index(fields=['name'], name='shipments_d_name_cc043f_idx'),
        ),
        migrations.AddIndex(
            model_name='loadingcompartment',
            index=models.Index(fields=['trip', 'compartment_number'], name='shipments_l_trip_id_28cb46_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='shipments_p_name_eff0a7_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['import_date'], name='shipments_s_import__f5e09b_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['product', 'destination'], name='shipments_s_product_35522c_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['quantity_remaining'], name='shipments_s_quantit_c458c8_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['user', 'import_date'], name='shipments_s_user_id_6ebf34_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['vessel_id_tag'], name='shipments_s_vessel__ec7448_idx'),
        ),
        migrations.AddIndex(
            model_name='shipmentdepletion',
            index=models.Index(fields=['trip'], name='shipments_s_trip_id_7bdeab_idx'),
        ),
        migrations.AddIndex(
            model_name='shipmentdepletion',
            index=models.Index(fields=['shipment_batch'], name='shipments_s_shipmen_c2bc39_idx'),
        ),
        migrations.AddIndex(
            model_name='shipmentdepletion',
            index=models.Index(fields=['created_at'], name='shipments_s_created_6bc9ec_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['loading_date'], name='shipments_t_loading_1e8a1e_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['status'], name='shipments_t_status_a535b3_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['kpc_order_number'], name='shipments_t_kpc_ord_a9fcd2_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['product', 'destination'], name='shipments_t_product_53a2d9_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['user', 'loading_date'], name='shipments_t_user_id_e409e2_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['plate_number'], name='shipments_v_plate_n_cd56bc_idx'),
        ),
    ]
