# Generated by Django 5.2.1 on 2025-06-03 08:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0017_customer_shipments_c_name_f4a852_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['product', 'import_date'], name='shipments_s_product_634bbf_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['supplier_name', 'import_date'], name='shipments_s_supplie_fb93fa_idx'),
        ),
        migrations.AddIndex(
            model_name='shipmentdepletion',
            index=models.Index(fields=['trip', 'created_at'], name='shipments_s_trip_id_3002d5_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['status', 'loading_date'], name='shipments_t_status_3b07e6_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['vehicle', 'loading_date'], name='shipments_t_vehicle_f2f62b_idx'),
        ),
    ]
