# Generated by Django 5.2.1 on 2025-07-14 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0021_userprofile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="whatsapp_enabled",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="department",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="telegram_chat_id",
            field=models.CharField(
                blank=True, help_text="Telegram chat ID", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phone_number",
            field=models.CharField(
                blank=True, help_text="WhatsApp phone number", max_length=20, null=True
            ),
        ),
    ]
