# Generated by Django 5.2.1 on 2025-08-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0022_alter_userprofile_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TR830ProcessingState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chat_id",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("filename", models.CharField(max_length=255)),
                ("import_date", models.DateTimeField()),
                ("vessel", models.CharField(max_length=100)),
                ("product_type", models.CharField(max_length=50)),
                ("destination", models.CharField(max_length=100)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=15)),
                ("description", models.TextField()),
                ("step", models.CharField(max_length=20)),
                ("user_id", models.IntegerField()),
                ("supplier", models.CharField(blank=True, max_length=200, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
    ]
