# Generated by Django 5.2.1 on 2025-08-21 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0023_tr830processingstate"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tr830processingstate",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "TR830 Processing State",
                "verbose_name_plural": "TR830 Processing States",
            },
        ),
        migrations.RemoveIndex(
            model_name="shipment",
            name="shipments_s_product_634bbf_idx",
        ),
        migrations.RemoveIndex(
            model_name="shipment",
            name="shipments_s_supplie_fb93fa_idx",
        ),
        migrations.RemoveField(
            model_name="tr830processingstate",
            name="user_id",
        ),
        migrations.AddField(
            model_name="tr830processingstate",
            name="user",
            field=models.ForeignKey(
                default=1,
                help_text="User processing this TR830",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="destination",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="historicalshipment",
            name="vessel_id_tag",
            field=models.CharField(
                db_index=True,
                help_text="Unique identifier for the vessel/shipment. This field is required and must be unique.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="historicaltrip",
            name="destination",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="shipments.destination",
            ),
        ),
        migrations.AlterField(
            model_name="historicaltrip",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending Authority"),
                    ("KPC_APPROVED", "KPC Approved"),
                    ("LOADING", "Loading in Progress"),
                    ("LOADED", "Loaded (BoL Issued)"),
                    ("GATEPASSED", "Gate Passed"),
                    ("TRANSIT", "In Transit"),
                    ("DELIVERED", "Delivered"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="vessel_id_tag",
            field=models.CharField(
                help_text="Unique identifier for the vessel/shipment. This field is required and must be unique.",
                max_length=100,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="tr830processingstate",
            name="chat_id",
            field=models.CharField(
                help_text="Telegram chat ID", max_length=50, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="tr830processingstate",
            name="description",
            field=models.TextField(help_text="Description from TR830"),
        ),
        migrations.AlterField(
            model_name="tr830processingstate",
            name="destination",
            field=models.CharField(help_text="Destination from TR830", max_length=200),
        ),
        migrations.AlterField(
            model_name="tr830processingstate",
            name="filename",
            field=models.CharField(
                help_text="Original filename of TR830 document", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="tr830processingstate",
            name="import_date",
            field=models.DateTimeField(help_text="Import date extracted from TR830"),
        ),
        migrations.AlterField(
            model_name="tr830processingstate",
            name="product_type",
            field=models.CharField(
                help_text="Product type (AGO, PMS, etc.)", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="tr830processingstate",
            name="quantity",
            field=models.DecimalField(
                decimal_places=2, help_text="Quantity in litres", max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="tr830processingstate",
            name="step",
            field=models.CharField(
                choices=[
                    ("supplier", "Waiting for Supplier"),
                    ("price", "Waiting for Price"),
                ],
                help_text="Current step in processing flow",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="tr830processingstate",
            name="supplier",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Supplier name entered by user",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="tr830processingstate",
            name="vessel",
            field=models.CharField(help_text="Vessel name from TR830", max_length=200),
        ),
        migrations.AlterField(
            model_name="trip",
            name="destination",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="shipments.destination"
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending Authority"),
                    ("KPC_APPROVED", "KPC Approved"),
                    ("LOADING", "Loading in Progress"),
                    ("LOADED", "Loaded (BoL Issued)"),
                    ("GATEPASSED", "Gate Passed"),
                    ("TRANSIT", "In Transit"),
                    ("DELIVERED", "Delivered"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddIndex(
            model_name="shipment",
            index=models.Index(
                fields=["supplier_name"], name="shipments_s_supplie_8b170e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tr830processingstate",
            index=models.Index(
                fields=["chat_id"], name="shipments_t_chat_id_d0bc18_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tr830processingstate",
            index=models.Index(
                fields=["user", "created_at"], name="shipments_t_user_id_a706b3_idx"
            ),
        ),
    ]
